---
title: "Homework#3 Final"
author: "Thakur Prasad Ghimire"
date: "9/30/2021"
output: word_document
---






```{r}
setwd("C:/HW#3/Homework#3 Final")
load("C:/HW#3/acs2017_ny_data.RData")
```



```{r echo=FALSE}
dat_NYC <- subset(acs2017_ny, (acs2017_ny$in_NYC == 1)&(acs2017_ny$AGE > 18) & (acs2017_ny$AGE < 66))
attach(dat_NYC)
borough_f <- factor((in_Bronx + 2*in_Manhattan + 3*in_StatenI + 4*in_Brooklyn + 5*in_Queens), levels=c(1,2,3,4,5),labels= c("Bronx","Manhattan","Staten Island","Brooklyn","Queens"))

```


```{r echo=TRUE}
norm_varb <- function(X_in) {
  (X_in - min(X_in, na.rm = TRUE))/( max(X_in, na.rm = TRUE) - min(X_in, na.rm = TRUE) )
}
```




```{r}
norm_varb <- function(X_in) {
  (max(X_in, na.rm = TRUE) - X_in)/( max(X_in, na.rm = TRUE) - min(X_in, na.rm = TRUE) )
}
is.na(OWNCOST) <- which(OWNCOST == 9999999)
housing_cost <- OWNCOST + RENT
norm_inc_tot <- norm_varb(INCTOT)
norm_housing_cost <- norm_varb(housing_cost)
data_use_prelim <- data.frame(norm_inc_tot,norm_housing_cost)
good_obs_data_use <- complete.cases(data_use_prelim,borough_f)
dat_use <- subset(data_use_prelim,good_obs_data_use)
y_use <- subset(borough_f,good_obs_data_use)
set.seed(12345)
NN_obs <- sum(good_obs_data_use == 1)
select1 <- (runif(NN_obs) < 0.8)
train_data <- subset(dat_use,select1)
test_data <- subset(dat_use,(!select1))
cl_data <- y_use[select1]
true_data <- y_use[!select1]
summary(cl_data)


```



```{r}

prop.table(summary(cl_data))


```


```{r}
summary(train_data)


```

```{r}
suppressMessages(require(class))
for (indx in seq(1, 9, by= 2)) {
 pred_borough <- knn(train_data, test_data, cl_data, k = indx, l = 0, prob = FALSE, use.all = TRUE)
num_correct_labels <- sum(pred_borough == true_data)
correct_rate <- (num_correct_labels/length(true_data))*100
print(c(indx,correct_rate))
print(summary(pred_borough))
}


```

```{r}

fam_pov <- POVERTY + FAMSIZE
norm_houseinc <- norm_varb(HHINCOME)
norm_fam_pov <- norm_varb(fam_pov)
data_use_prelim <- data.frame(norm_houseinc,norm_fam_pov)
good_obs_data_use <- complete.cases(data_use_prelim,borough_f)
dat_use <- subset(data_use_prelim,good_obs_data_use)
y_use <- subset(borough_f,good_obs_data_use)
set.seed(12345)
NN_obs <- sum(good_obs_data_use == 1)
select1 <- (runif(NN_obs) < 0.8)
train_data <- subset(dat_use,select1)
test_data <- subset(dat_use,(!select1))
cl_data <- y_use[select1]
true_data <- y_use[!select1]
summary(cl_data)

```

```{r}

prop.table(summary(cl_data))

```


```{r}
summary(train_data)


```


```{r}
summary(test_data)

```

```{r}
suppressMessages(require(class))
for (indx in seq(1, 9, by= 2)) {
 pred_borough1 <- knn(train_data, test_data, cl_data, k = indx, l = 0, prob = FALSE, use.all = TRUE)
num_correct_labels <- sum(pred_borough1 == true_data)
correct_rate <- (num_correct_labels/length(true_data))*100
print(c(indx,correct_rate))
print(summary(pred_borough1))
}
```


```{r}
utility_cost <- COSTELEC + COSTFUEL + COSTGAS + COSTWATR
norm_houseinc2 <- norm_varb(HHINCOME)
norm_utility_cost <- norm_varb(utility_cost)
data_use_prelim <- data.frame(norm_houseinc2,norm_utility_cost)
good_obs_data_use <- complete.cases(data_use_prelim,borough_f)
dat_use <- subset(data_use_prelim,good_obs_data_use)
y_use <- subset(borough_f,good_obs_data_use)
set.seed(12345)
NN_obs <- sum(good_obs_data_use == 1)
select1 <- (runif(NN_obs) < 0.8)
train_data <- subset(dat_use,select1)
test_data <- subset(dat_use,(!select1))
cl_data <- y_use[select1]
true_data <- y_use[!select1]
summary(cl_data)


```

```{r}

prop.table(summary(cl_data))

```


```{r}
summary(train_data)
```

```{r}
summary(test_data)

```

```{r}

suppressMessages(require(class))
for (indx in seq(1, 9, by= 2)) {
 pred_borough2 <- knn(train_data, test_data, cl_data, k = indx, l = 0, prob = FALSE, use.all = TRUE)
num_correct_labels <- sum(pred_borough2 == true_data)
correct_rate <- (num_correct_labels/length(true_data))*100
print(c(indx,correct_rate))
print(summary(pred_borough2))
}

```
